version: '3.9'
services:
  llm:
    image: ollama/ollama:0.1v
    ports:
      - 11434:11434
    volumes:
      - .:/home
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver : nvidia
    #           capabilities: [gpu]
    tty:
      true
    networks:
      - backend
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres-db-volume:/var/lib/postgresql/data
    ports:
      -  5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      - backend
networks:
  backend:
    driver: bridge
volumes:
  postgres-db-volume:
